# Generated by Django 5.2.6 on 2025-10-26 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalkey',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC_GAMES', 'PC Games'), ('CONSOLE_GAMES', 'Console Games'), ('ACCESSORIES', 'Gaming Accessories'), ('MOBILE', 'Mobile Gaming'), ('DEVICES', 'Gaming Devices')], default='PC_GAMES', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='PC_GAMES', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X'), ('SWITCH', 'Nintendo Switch'), ('MOBILE', 'Mobile'), ('MULTI', 'Multiple Platforms')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
