# Generated by Django 5.2.6 on 2025-10-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_digitalkey_product_remove_product_title_and_more'),
        ('orders', '0002_remove_order_paid_remove_order_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalKey',
        ),
    ]
